// Code generated by go-swagger; DO NOT EDIT.

package subscribe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UnsubscribeOKCode is the HTTP code returned for type UnsubscribeOK
const UnsubscribeOKCode int = 200

/*UnsubscribeOK OK

swagger:response unsubscribeOK
*/
type UnsubscribeOK struct {
}

// NewUnsubscribeOK creates UnsubscribeOK with default headers values
func NewUnsubscribeOK() *UnsubscribeOK {

	return &UnsubscribeOK{}
}

// WriteResponse to the client
func (o *UnsubscribeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UnsubscribeUnauthorizedCode is the HTTP code returned for type UnsubscribeUnauthorized
const UnsubscribeUnauthorizedCode int = 401

/*UnsubscribeUnauthorized unauthorized

swagger:response unsubscribeUnauthorized
*/
type UnsubscribeUnauthorized struct {
}

// NewUnsubscribeUnauthorized creates UnsubscribeUnauthorized with default headers values
func NewUnsubscribeUnauthorized() *UnsubscribeUnauthorized {

	return &UnsubscribeUnauthorized{}
}

// WriteResponse to the client
func (o *UnsubscribeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// UnsubscribeInternalServerErrorCode is the HTTP code returned for type UnsubscribeInternalServerError
const UnsubscribeInternalServerErrorCode int = 500

/*UnsubscribeInternalServerError internal server error

swagger:response unsubscribeInternalServerError
*/
type UnsubscribeInternalServerError struct {
}

// NewUnsubscribeInternalServerError creates UnsubscribeInternalServerError with default headers values
func NewUnsubscribeInternalServerError() *UnsubscribeInternalServerError {

	return &UnsubscribeInternalServerError{}
}

// WriteResponse to the client
func (o *UnsubscribeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
