// Code generated by go-swagger; DO NOT EDIT.

package subscribe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/statusdev/status/api/v1/models"
)

// NewUnsubscribeParams creates a new UnsubscribeParams object
// no default values defined in spec.
func NewUnsubscribeParams() UnsubscribeParams {

	return UnsubscribeParams{}
}

// UnsubscribeParams contains all the bound params for the unsubscribe operation
// typically these are obtained from a http.Request
//
// swagger:parameters unsubscribe
type UnsubscribeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*SubscriberDetails object that needs to be removed
	  Required: true
	  In: body
	*/
	Body *models.Subscriber
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUnsubscribeParams() beforehand.
func (o *UnsubscribeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Subscriber
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
