// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi status OpenAPI

    Schemes:
      https
    Host: cbrgm.net
    BasePath: /
    Version: 1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <chris@cbrgm.net>

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
