// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "status OpenAPI",
    "contact": {
      "email": "chris@cbrgm.net"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "cbrgm.net",
  "basePath": "/",
  "paths": {
    "/notifications": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "get the current status to the instance",
        "operationId": "notify",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/status": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "get the current status to the instance",
        "operationId": "getStatus",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Status"
              }
            }
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "add a new status to the instance",
        "operationId": "setStatus",
        "parameters": [
          {
            "type": "file",
            "description": "The media to upload",
            "name": "media",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/subscribers": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscribe"
        ],
        "summary": "subscribes to the instance",
        "operationId": "subscribe",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subscriber"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscribe"
        ],
        "summary": "subscribes to the instance",
        "operationId": "unsubscribe",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be removed",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subscriber"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Status": {
      "description": "SubscriberDetails describes a new subscriber who wants to get updates from the instance",
      "type": "object",
      "properties": {
        "caption": {
          "type": "string",
          "example": "My super cool picture"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "media": {
          "type": "string",
          "example": "https://foo.bar.com/myimg.png"
        }
      }
    },
    "Subscriber": {
      "description": "SubscriberDetails describes a new subscriber who wants to get updates from the instance",
      "type": "object",
      "properties": {
        "alias": {
          "type": "string",
          "example": "John Wick"
        },
        "url": {
          "type": "string",
          "example": "foo.bar.com"
        }
      }
    }
  },
  "tags": [
    {
      "description": "provides endpoints to subscribe to an instance",
      "name": "subscribe"
    },
    {
      "description": "provides endpoints to interact with an instance status",
      "name": "status"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "status OpenAPI",
    "contact": {
      "email": "chris@cbrgm.net"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "cbrgm.net",
  "basePath": "/",
  "paths": {
    "/notifications": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "get the current status to the instance",
        "operationId": "notify",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/status": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "get the current status to the instance",
        "operationId": "getStatus",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Status"
              }
            }
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "status"
        ],
        "summary": "add a new status to the instance",
        "operationId": "setStatus",
        "parameters": [
          {
            "type": "file",
            "description": "The media to upload",
            "name": "media",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/subscribers": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscribe"
        ],
        "summary": "subscribes to the instance",
        "operationId": "subscribe",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be accepted",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subscriber"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscribe"
        ],
        "summary": "subscribes to the instance",
        "operationId": "unsubscribe",
        "parameters": [
          {
            "description": "SubscriberDetails object that needs to be removed",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Subscriber"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "unauthorized"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Status": {
      "description": "SubscriberDetails describes a new subscriber who wants to get updates from the instance",
      "type": "object",
      "properties": {
        "caption": {
          "type": "string",
          "example": "My super cool picture"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "media": {
          "type": "string",
          "example": "https://foo.bar.com/myimg.png"
        }
      }
    },
    "Subscriber": {
      "description": "SubscriberDetails describes a new subscriber who wants to get updates from the instance",
      "type": "object",
      "properties": {
        "alias": {
          "type": "string",
          "example": "John Wick"
        },
        "url": {
          "type": "string",
          "example": "foo.bar.com"
        }
      }
    }
  },
  "tags": [
    {
      "description": "provides endpoints to subscribe to an instance",
      "name": "subscribe"
    },
    {
      "description": "provides endpoints to interact with an instance status",
      "name": "status"
    }
  ]
}`))
}
