// Code generated by go-swagger; DO NOT EDIT.

package subscribers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemoveSubscriberHandlerFunc turns a function with the right signature into a remove subscriber handler
type RemoveSubscriberHandlerFunc func(RemoveSubscriberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveSubscriberHandlerFunc) Handle(params RemoveSubscriberParams) middleware.Responder {
	return fn(params)
}

// RemoveSubscriberHandler interface for that can handle valid remove subscriber params
type RemoveSubscriberHandler interface {
	Handle(RemoveSubscriberParams) middleware.Responder
}

// NewRemoveSubscriber creates a new http.Handler for the remove subscriber operation
func NewRemoveSubscriber(ctx *middleware.Context, handler RemoveSubscriberHandler) *RemoveSubscriber {
	return &RemoveSubscriber{Context: ctx, Handler: handler}
}

/*RemoveSubscriber swagger:route DELETE /subscribers subscribers removeSubscriber

subscribes to the instance

*/
type RemoveSubscriber struct {
	Context *middleware.Context
	Handler RemoveSubscriberHandler
}

func (o *RemoveSubscriber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveSubscriberParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
