// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddStatusOKCode is the HTTP code returned for type AddStatusOK
const AddStatusOKCode int = 200

/*AddStatusOK OK

swagger:response addStatusOK
*/
type AddStatusOK struct {
}

// NewAddStatusOK creates AddStatusOK with default headers values
func NewAddStatusOK() *AddStatusOK {

	return &AddStatusOK{}
}

// WriteResponse to the client
func (o *AddStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddStatusUnauthorizedCode is the HTTP code returned for type AddStatusUnauthorized
const AddStatusUnauthorizedCode int = 401

/*AddStatusUnauthorized unauthorized

swagger:response addStatusUnauthorized
*/
type AddStatusUnauthorized struct {
}

// NewAddStatusUnauthorized creates AddStatusUnauthorized with default headers values
func NewAddStatusUnauthorized() *AddStatusUnauthorized {

	return &AddStatusUnauthorized{}
}

// WriteResponse to the client
func (o *AddStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddStatusInternalServerErrorCode is the HTTP code returned for type AddStatusInternalServerError
const AddStatusInternalServerErrorCode int = 500

/*AddStatusInternalServerError internal server error

swagger:response addStatusInternalServerError
*/
type AddStatusInternalServerError struct {
}

// NewAddStatusInternalServerError creates AddStatusInternalServerError with default headers values
func NewAddStatusInternalServerError() *AddStatusInternalServerError {

	return &AddStatusInternalServerError{}
}

// WriteResponse to the client
func (o *AddStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
