// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NotifyOKCode is the HTTP code returned for type NotifyOK
const NotifyOKCode int = 200

/*NotifyOK OK

swagger:response notifyOK
*/
type NotifyOK struct {
}

// NewNotifyOK creates NotifyOK with default headers values
func NewNotifyOK() *NotifyOK {

	return &NotifyOK{}
}

// WriteResponse to the client
func (o *NotifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// NotifyUnauthorizedCode is the HTTP code returned for type NotifyUnauthorized
const NotifyUnauthorizedCode int = 401

/*NotifyUnauthorized unauthorized

swagger:response notifyUnauthorized
*/
type NotifyUnauthorized struct {
}

// NewNotifyUnauthorized creates NotifyUnauthorized with default headers values
func NewNotifyUnauthorized() *NotifyUnauthorized {

	return &NotifyUnauthorized{}
}

// WriteResponse to the client
func (o *NotifyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// NotifyInternalServerErrorCode is the HTTP code returned for type NotifyInternalServerError
const NotifyInternalServerErrorCode int = 500

/*NotifyInternalServerError internal server error

swagger:response notifyInternalServerError
*/
type NotifyInternalServerError struct {
}

// NewNotifyInternalServerError creates NotifyInternalServerError with default headers values
func NewNotifyInternalServerError() *NotifyInternalServerError {

	return &NotifyInternalServerError{}
}

// WriteResponse to the client
func (o *NotifyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
