// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RemoveSubscriptionHandlerFunc turns a function with the right signature into a remove subscription handler
type RemoveSubscriptionHandlerFunc func(RemoveSubscriptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveSubscriptionHandlerFunc) Handle(params RemoveSubscriptionParams) middleware.Responder {
	return fn(params)
}

// RemoveSubscriptionHandler interface for that can handle valid remove subscription params
type RemoveSubscriptionHandler interface {
	Handle(RemoveSubscriptionParams) middleware.Responder
}

// NewRemoveSubscription creates a new http.Handler for the remove subscription operation
func NewRemoveSubscription(ctx *middleware.Context, handler RemoveSubscriptionHandler) *RemoveSubscription {
	return &RemoveSubscription{Context: ctx, Handler: handler}
}

/*RemoveSubscription swagger:route DELETE /subscriptions subscriptions removeSubscription

unsubscribe from a remote  instance

*/
type RemoveSubscription struct {
	Context *middleware.Context
	Handler RemoveSubscriptionHandler
}

func (o *RemoveSubscription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveSubscriptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
